// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Message = { user_id: number, channel_id: number, server_id: number, ts: string, id: bigint, text: string, };
