// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Channel } from "./Channel";
import type { Message } from "./Message";
import type { Server } from "./Server";
import type { User } from "./User";

export type Update = { "User": User } | { "Server": Server } | { "Channel": Channel } | { "Message": Message };
