// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VoiceSignal = { "type": "Join", user_id: number, channel_id: number, } | { "type": "Leave", user_id: number, channel_id: number, } | { "type": "Offer", from: number, to: number, channel_id: number, sdp: string, } | { "type": "Answer", from: number, to: number, channel_id: number, sdp: string, } | { "type": "IceCandidate", from: number, to: number, channel_id: number, candidate: string, };
